### ISSUE TITLE
Reduce access to `ii`

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/org#2]
Pair is an ii internal tool, but open and available for others to run.
For our Pair in production, reduce the access back to the `ii` org.

**Comment by zachmandeville** [comment]
I think this is a good idea, especially since the open access implies there is onboarding and an easier experience for new users, which there isn't.

Onboarding and a great user experience are goals for the new version of Pair, but if they aren't going to be added to "Pair in Production" and we are saying that this is just in bare maintenance mode, then I think it would be good to limit it until we can serve the public better.

**Comment by hh** [comment]
Let's hold off on this for now.

**Comment by hh** [comment]
I recognise and sent each of those people who created instances recently..
Easier to leave open and clean up boxes than for me to need to setup / change access.

**Comment by BobyMCbobs** [comment]
> I think this is a good idea, especially since the open access implies there is onboarding and an easier experience for new users, which there isn't.
> 
> Onboarding and a great user experience are goals for the new version of Pair, but if they aren't going to be added to "Pair in Production" and we are saying that this is just in bare maintenance mode, then I think it would be good to limit it until we can serve the public better.

@zachmandeville, I think you made some very valid points

**Comment by riaankleinhans** [comment]
If we leave it open I would surgest that we clean-up all open Pair boxes that do not belong to an ii human once a week.
